services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-main
    environment:
      - N8N_RUNNERS_MODE=internal
      - N8N_NATIVE_PYTHON_RUNNER=true
      - N8N_PYTHON_ALLOWED_MODULES=random,math,json,datetime
    ports:
      - "5679:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./results:/home/node/results
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6334:6333"
    volumes: 
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  n8n_data: