services:
  n8n:
    image: n8nio/n8n@sha256:a49bc161141d6c4b9c495b5a6e3c7c1932e61d2ed2fe3fdca01262064b4b23ca
    container_name: n8n-main
    environment:
      - N8N_RUNNERS_MODE=internal
      - N8N_NATIVE_PYTHON_RUNNER=true
      - N8N_PYTHON_ALLOWED_MODULES=random,math,json,datetime
    ports:
      - "5679:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./results:/home/node/results
      - ./RAG_documents:/home/node/RAG_documents
      - .d/RAG_documents:/home/node/.n8n-files
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n_data: